### ISSUE TITLE
Redirect repo to wardenenv/homebrew-warden

### ISSUE THREAD

**Issue by ihor-sviziev** [davidalger/homebrew-warden#3]
Hi @davidalger,

This repo wasn't moved to https://github.com/wardenenv/homebrew-warden as part of migrating Warden to https://github.com/wardenenv.
As a result you still can install an old warden version using `brew install davidalger/warden/warden`.

It happened to my colleague that he found this old command in some internal readme file, as a result it was hard to understand what was wrong - why the project works fine on my computer, but not on his.

Could you please remove this repo with a redirect to a new one in order to prevent such situations in the future? 

Thank you!
PS: Looks like I'm not the only one, and this one is related https://github.com/davidalger/homebrew-warden/pull/2 

/cc @navarr

**Comment by navarr** [comment]
I've been meaning to keep this up to date as a mirror.  That's on me.  I've updated it to the recent version
